### ISSUE TITLE
Bug report: Text selection broken on Navercast

### ISSUE THREAD

**Issue by alanhogan** [alanhogan/bookmarklets#1]
>   Hi,
>       Thank you for sharing very useful "Allow Text 
>     Selection" bookmarklet of yours. However there are 
>     some cases where I'm afraid the bookmarklet fails to 
>     work, and while I simply give up most of them there 
>     is just one site big enough that if the bookmarklet 
>     can work with the website it would be of great use 
>     to me.
>     See following website:
>     http://navercast.naver.com/magazine_contents.nhn?rid=2267&attrId=&contents_id=80422&leafId=2267
>     You can try and see under current version of chrome 
>     (windows 8.1 x64) bookmarklet cannot fix their 
>     blocking of right click nor text selection.
>     It'd be great if a fix can be made available for the 
>     technique that this website uses!
>     Thanks.

**Comment by alanhogan** [comment]
Not sure what technique that site is using. I am already attempting to disrupt 'mousedown'-based approaches (note you cannot select or right-click _anything_ on this website), as well as common CSS-based ones. Input welcome.

**Comment by RoxKilly** [comment]
I have no trouble copying text, even without using bookmarklet. Are you referring to any specific part of the page?

**Comment by alanhogan** [comment]
They probably un-broke their own site at some point :)
