### ISSUE TITLE
[enable-text-selection.js] Remove jQuery dependency

### ISSUE THREAD

**Issue by RoxKilly** [alanhogan/bookmarklets#4]
I'm a big fan of this little script (`enable-text-selection`); thanks for sharing it with us. I had it as a bookmarklet for a long time but recently switched to using it as a user script with `Greasemonkey`. It has always bugged me though that a script this small depends on a much bigger framework (jQuery) mostly so it can use its selector and attribute setting functions.  Why not use the [native JavaScript selector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) `document.querySelectorAll()` which has basically the same syntax, and the [native attribute settor](https://developer.mozilla.org/en/docs/Web/API/Element/setAttribute) `setAttribute()`?  It would drastically reduce (by about 95%) the impact your script has on browser memory (not to mention bandwidth and page load time) when used on those sites that don't already use jQuery.

Enable-text-selection.js: 1.9KB
JQuery 1.9.1 minified: 90.5KB

**Comment by alanhogan** [comment]
Sure. It’s an old script from back when jQuery did a lot that browsers didn’t.

Want to take a stab at it, with a pull request?

— Hogan

**Comment by RoxKilly** [comment]
Thanks for the invitation. This will be my first ever pull request (I'm learning JavaScript, version control concepts... right now) so you'll want to check my work. If you're still open to it I'd love to try.

**Comment by alanhogan** [comment]
How exciting. No, I certainly wouldn't mind reviewing your PR!

— Hogan

**Comment by RoxKilly** [comment]
Alan do you control a setting to allow/disallow non-contributors from making pull requests? I get [permission denied error](http://stackoverflow.com/questions/37760476/github-push-permission-denied-over-both-ssh-and-https). I'd post the details here but it seems off-topic

**Comment by alanhogan** [comment]
Did you fork? You're probably trying to push to my repo, which would cause a permission error. 

Alan

**Comment by RoxKilly** [comment]
I think I did it. Thank you.

PS. for anyone who comes across this and wonders the same thing: I had to create a fork (sign in, go to repo and click `fork` at top right of the page), make changes to that fork (pull it to my machine, commit my edits, and push changes to the fork), and select `New Pull Request` on the Github webpage for my fork. [Here is the guide.](https://help.github.com/articles/using-pull-requests/)

**Comment by RoxKilly** [comment]
I get that you're prob busy with more important things; Not quite sure why you invited me to do a PR though if you wouldn't take a look at it after.

**Comment by alanhogan** [comment]
I didn’t see it. I’ll take a look soon!

**Comment by alanhogan** [comment]
thanks for submitting a PR for this and making improvements!

**Comment by RoxKilly** [comment]
No problem. Cheers.
